import {GoogleGenerativeAI, SchemaType} from '@google/generative-ai';
import dotenv from 'dotenv';
import {AnalysisResult} from '../types/index.js';

dotenv.config();

// Initialize the Google Generative AI client with the API Key from environment
// variables
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || '');

/**
 * RESPONSE SCHEMA DEFINITION
 * This schema acts as a "contract" for the AI.
 * It forces the LLM to return a valid JSON object instead of raw text,
 * ensuring our backend can consistently parse the scores and tiering.
 */
const schema = {
  type: SchemaType.OBJECT,
  properties: {
    candidateName: {type: SchemaType.STRING},
    scores: {
      type: SchemaType.OBJECT,
      properties: {
        exact: {type: SchemaType.NUMBER},       // Direct skill matching
        similarity: {type: SchemaType.NUMBER},  // Contextual/Domain similarity
        impact: {type: SchemaType.NUMBER},      // Quantifiable achievements
        ownership:
            {type: SchemaType.NUMBER},  // Leadership/Responsibility level
      },
      required: ['exact', 'similarity', 'impact', 'ownership'],
    },
    explanation: {type: SchemaType.STRING},  // Brief reasoning for the score
    tier: {
      type: SchemaType.STRING,
      enum: [
        'Tier A (Fast-track)', 'Tier B (Technical Screen)',
        'Tier C (Needs Evaluation)'
      ]
    },
  },
  required: ['candidateName', 'scores', 'explanation', 'tier'],
};

/**
 * analyzeResume
 * Core function that sends the Job Description (JD) and Resume text to Gemini.
 * @param resumeText - The extracted text from the candidate's PDF
 * @param jdText - The extracted text from the Job Description PDF
 * @returns A structured AnalysisResult object
 */
export const analyzeResume =
    async(resumeText: string, jdText: string): Promise<AnalysisResult> => {
  // Define the specific model version to use
  const model = genAI.getGenerativeModel({
    model: 'gemini-2.5-flash',
  });

  /**
   * PROMPT ENGINEERING
   * We give the AI a persona (Senior Technical Recruiter) and
   * explicit rules for how to categorize candidates into Tiers.
   */
  const prompt = `
  Act as a Senior Technical Recruiter. Evaluate the following resume against the Job Description (JD).
  
  CLASSIFICATION LOGIC:
  - Tier A (Fast-track): High scores in all dimensions (>85%). Exceptional technical match and clear quantifiable impact.
  - Tier B (Technical Screen): Strong match but might have small skill gaps or fewer quantifiable achievements. Good potential.
  - Tier C (Needs Evaluation): Lower alignment with the tech stack or lacks the required experience level.

  JD: ${jdText}
  RESUME: ${resumeText}
`;

  // Execute the AI generation request
  const result = await model.generateContent({
    contents: [{role: 'user', parts: [{text: prompt}]}],
    generationConfig: {
      // JSON mode ensures the output matches our defined schema exactly
      responseMimeType: 'application/json',
      responseSchema: schema,
    },
  });

  /**
   * PARSING THE RESPONSE
   * result.response.text() returns the JSON string generated by the AI.
   * We parse it into a JavaScript object to be used by the router.
   */
  return JSON.parse(result.response.text());
};